fix(ci): Test automatic retries on the selenium tests
I keep getting these kinds of exceptions, which are enough to drive me
mad:

```
======================================================================
FAIL: test_logged_in_user_can_save_favorite (cl.favorites.tests.UserFavoritesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
    return function(*args, **kwargs)
  File "/opt/courtlistener/cl/favorites/tests.py", line 220, in test_logged_in_user_can_save_favorite
    self.click_link_for_new_page(short_title)
  File "/opt/courtlistener/cl/tests/base.py", line 115, in click_link_for_new_page
    self.browser.find_element_by_link_text(link_text).click()
  File "/usr/local/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/opt/courtlistener/cl/tests/base.py", line 111, in wait_for_page_load
    WebDriverWait(self.browser, timeout).until(staleness_of(old_page))
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 77, in until
    time.sleep(self._poll)
  File "/usr/local/lib/python2.7/site-packages/timeout_decorator/timeout_decorator.py", line 72, in handler
    _raise_exception(timeout_exception, exception_message)
  File "/usr/local/lib/python2.7/site-packages/timeout_decorator/timeout_decorator.py", line 45, in _raise_exception
    raise exception()
TimeoutError: u'Timed Out'
```