fix(importers): Cast queryset to list
During upgrade to Django 2.0, I ran into an issue that:

    ValueError: The QuerySet value for an exact lookup must be limited
     to one result using slicing.

Something about the way this line does slicing of the QuerySet:

    case_names = [s[0] for s in case_data]

Was triggering that. I'm hopeful that by casting to a list, the issue
should be fixed.