fix(opinion_page): silenced some mypy errors
I don't understand these:

cl/opinion_page/views.py:673: error: Incompatible type for
lookup 'docket_entry__docket_id': (got "int | None", expected "str | int")
[misc]

A docket_id is an int.  Casting this to a str fixes the error, but that isn't
correct.

cl/opinion_page/views.py:865: error: Dict entry 0 has incompatible
type "str": "int | None"; expected "str": "str | None"  [dict-item]

I'm assigning a [str: int | None] to a dict that is [str, str | int | None], but
mypy claims it is [str: str | None].

cl/opinion_page/views.py:882: error: Incompatible return value type (got "list
[dict[str, str | None]]", expected "list[dict[str, str | int | None]]")
[return-value]

At 865, it complained that I assigned a [str: int | None] to this dicts in this
list, now it complains that it is only [str, str | None].  Yes, if you ignore
the ints being added to the dict, then it appears to not have any ints in it.