feat(opinions): Add support for Harvard data
This commit adds support for cases from the Caselaw Access Project. Included in this commit are two major features:

1. The model is updated to support all the fields that come from CAP.

2. A new file, `harvard_opinions.py` is now available as a management
command to import CAP cases from JSON files.

It also includes one major cleanup:

1. Text fields that were previously needlessly nullable now use the Django convention of being blank when empty.

------

* feat(issue-1029-tax-opinions): Create download from IA command

* refactor(issue-1029-tax-opinions): Move cl_scrape_ia search -> scrapers

* refactor(issue-1029-tax-opinions): Cleanup from PR #1074

Streamline cl_scrape_ia to only download to disk. Use mkdir_p
to streamline file saving.  Valid_actions no longer required.

* refactor(issue-1029-tax-opinions): Requested changes for PR

* refactor(issue-1029-tax-opinions): More Cleanup from PR #1074

Renamed file to scrape_harvard_ia

* feature(issue-1029-tax-opinions): Cleanup tax court opinions

Scraped Tax cases are missing citations and docket numbers that are
within the document itself.

* test(issue-1029-tax-opinions): Add non standard tests to citation

* chore(issue-1029-tax-opinions): Whitespace and line length cleanup

* test(issue-1029-tax-opinions): Add citation parsing for Cleanup tests

* feat(import-harvard): Add html_harvard to view_opinion.html template

* feat(import opinions): Init harvard_opinions importer command file

* tests(import opinions): Create HarvardTest class for import testing

* feat(opinion model): Add Harvard and associated key to Docket sources

* feat(opinion model): Add new fields to OpinionCluster in Harvard data

* feat(opinion model): Add new Opinion_Types to Opinion Model

* feat(opinion model): Add joined_by_str to opinion object

* feat(opinion model): Add html_harvard to opinion object

* feat(merge-harvard): Allow new duplicate cite cases to proceed if unique

* feat(merge-harvard): Make migration file and sql file

* feat(black): Blackify files pre merge

* style(black): Cleanup

* fix(tests): Fix merge error that created a duplicate test

* refactor(importers): Move file path filtering to its own function and make it sorted

* feat(importers): Better docstrings and logging

* refactor(importer): Variable normalization and minor tweaks

* fix(harvard_opinions) Remove first person narrative in comment field

* fix(harvard_opinions) Remove un-needed str call for dates

* fix(harvard_opinions) Update data model names and help_text

other_date --> other_dates
html_harvard x2 --> xml_harvard

* fix(harvard_opinions) Update migration/sql to match model

* fix(template) Update template for new field name xml_harvard

* feat(harvard_opinions) Add transaction to save method

* feat(harvard_opinions) Add save method to transaction

* feat(harvard_opinions) Create new function to check case duplicate

* feat(harvard_opinions) Implement duplicate citations

* feat(harvard_opinions) Add smart titling of judge names

* feat(harvard_opinions) Add updated harvard migration

* Merge remote-tracking branch 'origin/1080-merge-harvard' into 1080-merge-harvard

Merges and conflicts applied

* fix(harvard-opinions) Black reformatting.

* fix(search-models) Black reformatting

* fix(regex) circuit regexes fix for failing tests

* fix(cleanup-tests) Fix tests for citation generation

* refactor(tax): Write better lookup functions

* refactor(tax): Move pg_count closer to where it's needed

* refactor(tax): Factor out the opinion type mapping

* refactor(tax): Refactor ifs into single dict + lookup

* feat(tax): Provide variables for all opinion types

* refactor(models): Use opinion type variables across code base

* refactor(citations): Factor out the citation type mapping

* refactor(citations): Simplify citation mapping function

Also: Correct the lexis and west parameters.

* refactor(citations): Factor out the citation type mapping globally

* feat(harvard): Add phrase normalization to the case name matcher

* refactor(harvard): Factor out dup and sanity checks

* refactor(harvard): Use `.exists` for check

This provides a slight performance benefit, but it's also an
improvement to the readability of the code, and a good habit to
remember to use.

* fix(search.models) Fix XML_harvard opinion help_text, remove null=True

* fix(fix_tax_court) Remove xml_harvard op_cluster

Reformatting correction sucked into commit.

* fix(fix_tax_court) Rename filepath_local ==> filepath_json_harvard

* fix(fix_tax_court) Remove sha1, page_count, image_missing from cluster

* fix(fix_tax_court) Remove null=True add blank=True for textfields

* fix(search.models) Black formatting for multiline help_text

* refactor(harvard_opinions) Update code to reflect model changes

sha1, page_count, image_missing removed
filepath_local renamed

* refactor(harvard_opinions) Remove unused sha1 crypto import

* refactor(harvard_opinions) import get_citations

* feat(harvard_opinions) Use get_citations function to streamline code

use generated citation object to test for duplicates

* refacotr(harvard_opinions) Use new citation object in code

* refactor(harvard_opinions) update filepath_local to filepath_json_harvard

* cleanup(harvard_opinions) Remove unused variable content

* cleanup(harvard_opinions) Fix whitespace

* fix(harvard_opinions) Add continue to citation not found

* fix(harvard_opinions) Update method to reflect model changes

* fix(harvard_opinions) Use citation.reporter in cite type mapping

One Whitespace tweak

* feat(corpus_importer tests) Add fixtures and assets

* feat(corpus.tests) Add newly required imports

* feat(corpus.tests) Create Harvard Opinions Testing class

* style(corpus.tests) Black cleanup

* fix(harvard_opinions) Update migration files for model changes

Includes sql file

* feat(harvard_opinions) Add Migration 0086 py file

* feat(harvard): Tune ups to tests during review

* feat(harvard): Tune up to harvard_opinions.py during review

* feat(models): Migrate the sources field in audio model (noop)

* feat(models): Add migration to set null fields to empty

This is needed because without it you get an error like:

```
↪ docker exec -it cl-django python /opt/courtlistener/manage.py migrate

Warning: No such file or directory: /var/log/juriscraper/debug.log. Have you created the directory for the log?
Juriscraper will continue to run, and all logs will be sent to stderr.
Operations to perform:
  Apply all migrations: admin, alerts, audio, auth, authtoken, contenttypes, donate, favorites, lasc, people_db, recap, recap_rss, scrapers, search, sessions, sites, stats, users, visualizations
Running migrations:
  Applying search.0086_add_harvard_opinions...Traceback (most recent call last):
  File "/opt/courtlistener/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 221, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 531, in alter_field
    old_db_params, new_db_params, strict)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/postgresql/schema.py", line 112, in _alter_field
    new_db_params, strict,
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 726, in _alter_field
    params,
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 136, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: cannot ALTER TABLE "search_opinion" because it has pending trigger events
```

That's caused by trying to change data and schemas at the same time, as discussed here:

https://stackoverflow.com/questions/12838111/django-db-migrations-cannot-alter-table-because-it-has-pending-trigger-events

The solution to that is to separate out the data migration from the schema migration.
This is the first step in that process. The next commit contains the schema migrations.

This could have been done via the Django API instead oF SQL but it seemed simpler and
more clear this way.

* feat(models): Update migration to make it depend on the data migration

This will break people's migrations if they do not go to 0085 before
pulling this code. I'm sorry. It was just easier for me.

I also recommend blowing away your postgresql docker container then
recreating and migrating it as a simple solution.

See previous commit for full discussion.

* feat(models): Remove claimshistory ALTER commands from this migration

It's now in its own migration 0085 that we pulled from master, so removing it
here is really just part of the merge process.

* fix(tests): Update fixtures to match new models

* fix(html): Don't show a link to the download URL when unavailable

We are pretty good about this generally, but when it's OCR'ed and lacks
such a value, we do badly.

Co-authored-by: Mike Lissner <mike@free.law>