fix(deps): Downgrade Redis to 3.1.x
This is the latest episode in our saga to find a functional combination of Celery, Redis, Kombu, and
Django. Since our upgrade to the latest Celery, we've had an issue when we run our nightly opinion
downloader, it works perfectly fine for a while and then throws the following mega exception:

Traceback (most recent call last):
  File "/var/www/courtlistener/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/www/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 270, in handle
    options['action'](options)
  File "/var/www/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 227, in do_everything
    get_and_save_free_document_reports(options)
  File "/var/www/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 119, in get_and_save_free_document_reports
    result = delay['result'].get()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/result.py", line 209, in get
    self._maybe_reraise_parent_error()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/result.py", line 232, in _maybe_reraise_parent_error
    node.maybe_throw()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/result.py", line 327, in maybe_throw
    cache = self._get_task_meta() if self._cache is None else self._cache
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/result.py", line 412, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/result.py", line 406, in _maybe_set_cache
    self.on_ready(self)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/vine/promises.py", line 170, in __call__
    return self.throw()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/vine/promises.py", line 167, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/result.py", line 123, in _on_fulfilled
    self.backend.remove_pending_result(self)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/backends/asynchronous.py", line 175, in remove_pending_result
    self.on_result_fulfilled(result)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/backends/asynchronous.py", line 183, in on_result_fulfilled
    self.result_consumer.cancel_for(result.id)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/backends/redis.py", line 148, in cancel_for
    self._pubsub.unsubscribe(key)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/redis/client.py", line 3112, in unsubscribe
    retval = self.execute_command('UNSUBSCRIBE', *args)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/redis/client.py", line 3009, in execute_command
    self._execute(connection, connection.send_command, *args)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/redis/client.py", line 3013, in _execute
    return command(*args)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/redis/connection.py", line 620, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/redis/connection.py", line 613, in send_packed_command
    (errno, errmsg))
redis.exceptions.ConnectionError: Error 32 while writing to socket. Broken pipe.

That's...not great. Researching the exception there's a lot of people complaining about it. Some in
the Celery bug tracker, others in the redis and various other trackers. After reading a bunch of
these issues, it became apparent that nobody knows what's going on here, but I did find a comment
in the rq repo that reads:

>>    I think this is caused by the newest version of RedisPy, which rq uses under the hood.

>>   Temp fix is to pin the version in your requirements file:

>>   redis >= 3.0, < 3.1

> Yep. this fixes it thanks.

(https://github.com/rq/rq/issues/1037#issuecomment-459778143)

So...fine, we'll try that, and hopefully that'll work. Checking the release notes for redis-py
(https://github.com/andymccurdy/redis-py/blob/master/CHANGES), 3.2 doesn't bring much to the table
that seems important, so I think this is fine.