fix(extractors): Attempt series of encodings to convert HTML to text
Better would be to use the values in the HTML's meta tags, but this should work fine for the corner
case we're dealing with. This was initiated because we were getting the following exceptions when
adding some HTML content to the DB:

****Error saving text to the db for: 2909583 - State v. Racheal Fowler****
Traceback (most recent call last):
  File "/var/www/courtlistener/cl/scrapers/tasks.py", line 248, in extract_doc_content
    opinion.save(index=False)
  File "/var/www/courtlistener/cl/search/models.py", line 1958, in save
    super(Opinion, self).save(*args, **kwargs)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/base.py", line 827, in _save_table
    forced_update)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/base.py", line 877, in _do_update
    return filtered._update(values) > 0
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/query.py", line 580, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
DataError: invalid byte sequence for encoding "UTF8": 0xa0