fix(iquery): Recreate redis connection upon failure
I'm running this in prod now and every 12 hours or so it is
crashing with some variation of:

Traceback (most recent call last):
  File "/opt/courtlistener/manage.py", line 15, in <module>
    main()
  File "/opt/courtlistener/manage.py", line 11, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/courtlistener/cl/corpus_importer/management/commands/bulk_iquery_project.py", line 111, in handle
    add_all_cases_to_cl(options)
  File "/opt/courtlistener/cl/corpus_importer/management/commands/bulk_iquery_project.py", line 71, in add_all_cases_to_cl
    raise e
  File "/opt/courtlistener/cl/corpus_importer/management/commands/bulk_iquery_project.py", line 59, in add_all_cases_to_cl
    pacer_case_id = r.hincrby("iquery_status", court_id, 1)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3018, in hincrby
    return self.execute_command('HINCRBY', name, key, amount)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 101, in sentry_patched_execute_command
    return old_execute_command(self, name, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 324, in read_response
    raw = self._buffer.readline()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 256, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 222, in _read_from_socket
    raise ConnectionError("Error while reading from socket: %s" %
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')

Seems like we can deal with this by recreating a new redis
connection when this happens. Let's see.