fix(api stats): Count stats for anonymous user properly
This was crashing in the latest update to redis due to:

    ERROR:cl.api.utils:Unable to log API response timing info: Invalid input of type: 'NoneType'. Convert to a byte, string or number first.
    Traceback (most recent call last):
      File "/var/www/courtlistener/cl/api/utils.py", line 172, in finalize_response
        results = self._log_request(request)
      File "/var/www/courtlistener/cl/api/utils.py", line 225, in _log_request
        results = pipe.execute()
      File "/var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/redis/client.py", line 3520, in execute
        return execute(conn, stack, raise_on_error)
      File "/var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/redis/client.py", line 3386, in _execute_transaction
        if EMPTY_RESPONSE not in options])
      File "/var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/redis/connection.py", line 687, in pack_commands
        for chunk in self.pack_command(*cmd):
      File "/var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/redis/connection.py", line 663, in pack_command
        for arg in imap(self.encoder.encode, args):
      File "/var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/redis/connection.py", line 125, in encode
        "byte, string or number first." % typename)
    DataError: Invalid input of type: 'NoneType'. Convert to a byte, string or number first.