Attempts to shrink the bundle size for tasks.
We've had some issues with the indexing failing because of connections getting dropped. I think this is because the items to index are too large when there's a big bundle size. Hopefully this will fix it. The stacktrace this should fix looks like:

Processed 22499/363218 (6%)Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/var/www/courtlistener/cl/search/management/commands/cl_update_index.py", line 160, in handle
    self.add_or_update_all()
  File "/var/www/courtlistener/cl/lib/timer.py", line 10, in wrapper
    res = func(*arg)
  File "/var/www/courtlistener/cl/search/management/commands/cl_update_index.py", line 451, in add_or_update_all
    self._chunk_queryset_into_tasks(q, count, bundle_size=bundle_size)
  File "/var/www/courtlistener/cl/search/management/commands/cl_update_index.py", line 230, in _chunk_queryset_into_tasks
    job.apply_async().join()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/result.py", line 642, in join
    interval=interval, no_ack=no_ack,
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/result.py", line 175, in get
    raise meta['result']
requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))