feat(idb merge): Do not update solr while merging rows
Alas, it throws lots of errors like this one if it cannot keep up:

Traceback (most recent call last):
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/courtlistener/cl/search/tasks.py", line 101, in add_or_update_recap_docket
    si = scorched.SolrInterface(settings.SOLR_RECAP_URL, mode='w')
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/scorched/connection.py", line 290, in __init__
    self.schema = self.init_schema()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/scorched/connection.py", line 296, in init_schema
    self.remote_schema_file))
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/scorched/connection.py", line 71, in request
    return self.http_connection.request(*args, **kwargs)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='192.168.0.130', port=8983): Max retries exceeded with url: /solr/recap/schema?wt=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4d10f47450>: Failed to establish a new connection: [Errno 111] Connection refused',))