fix(recap): Remove errant call to ClaimsHistory.pacer_seq_no
In prod, this caused:

AttributeError                            Traceback (most recent call last)
<ipython-input-11-c89b39bbc377> in <module>()
----> 1 process_recap_claims_register(pq.pk)

/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/local.pyc in __call__(self, *a, **kw)
    189
    190     def __call__(self, *a, **kw):
--> 191         return self._get_current_object()(*a, **kw)
    192
    193     def __len__(self):

/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/app/task.pyc in __call__(self, *args, **kwargs)
    392         self.push_request(args=args, kwargs=kwargs)
    393         try:
--> 394             return self.run(*args, **kwargs)
    395         finally:
    396             self.pop_request()

/var/www/courtlistener/cl/recap/tasks.pyc in process_recap_claims_register(self, pk)
    760
    761     add_bankruptcy_data_to_docket(d, data)
--> 762     add_claims_to_docket(d, data["claims"])
    763     logger.info("Created/updated claims data for %s", pq)
    764

/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/utils/decorators.pyc in inner(*args, **kwargs)
    183             def inner(*args, **kwargs):
    184                 with self:
--> 185                     return func(*args, **kwargs)
    186             return inner
    187

/var/www/courtlistener/cl/recap/mergers.pyc in add_claims_to_docket(d, new_claims, tag_names)
   1083
   1084         for new_history in new_claim["history"]:
-> 1085             add_claim_history_entry(new_history, db_claim)
   1086
   1087

/var/www/courtlistener/cl/recap/mergers.pyc in add_claim_history_entry(new_history, claim)
    997         )
    998         db_history.pacer_seq_no = (
--> 999             new_history.get("pacer_seq_no") or db_history.pacer_seq_no
   1000         )
   1001     else:

AttributeError: 'ClaimHistory' object has no attribute 'pacer_seq_no'