fix(views): Pass result of function not function itself in returned value
I don't know why this breaks in the latest django, but it does. Previously we were able to cache
the response like this, but we can't anymore. In testing this returns intermittent errors like:

    ERROR:django.request:Internal Server Error: /opinion/
    Traceback (most recent call last):
      File "/var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
        response = get_response(request)
      File "/var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
        response = self.process_exception_by_middleware(e, request)
      File "/var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/var/www/courtlistener/cl/search/views.py", line 352, in advanced
        cache.set(o_cache_key, o_results, six_hours)
      File "/var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/redis_cache/backends/base.py", line 30, in wrapped
        return method(self, client, key, *args, **kwargs)
      File "/var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/redis_cache/backends/base.py", line 274, in set
        result = self._set(client, key, self.prep_value(value), timeout, _add_only=False)
      File "/var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/redis_cache/backends/base.py", line 219, in prep_value
        value = self.serialize(value)
      File "/var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/redis_cache/backends/base.py", line 197, in serialize
        return self.serializer.serialize(value)
      File "/var/www/.virtualenvs/courtlistener/lib/python2.7/site-packages/redis_cache/serializers.py", line 39, in serialize
        return pickle.dumps(value, self.pickle_version)
    PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

Which seems to be what happens when you try to pickle a function. In debugging this error goes away,
I think because the function gets run *by the debugger* and thus serialized. Anyway, I think by
running the function instead of passing it, the error should be resolved.