fix(recap docket api): Fixes lookups that match on docket number only.
Currently we attempt to look up an item by docket number + pacer_case_id, then by pacer_case_id,
then by docket number. If the third one works, we need to make sure there's a pacer_case_id in
the resulting docket or else we get a validation failure in the save routine that looks like:

Traceback (most recent call last):
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/courtlistener/cl/recap/tasks.py", line 607, in process_recap_docket
    d.save()
  File "/var/www/courtlistener/cl/search/models.py", line 302, in save
    "RECAP documents." % field)
ValidationError: [u"'pacer_case_id' cannot be Null or empty in RECAP documents."]

So, this fixes that by ensuring that we have a pacer_case_id if one was previously missing.