fix(opinion scraper): Makes opinion scraper more synchronous
Unfortunately, this is needed because of issues with new versions of Redis and Celery. Currently,
when a connection fails, as it inevitably does, it crashes this script, throwing an error like:

Traceback (most recent call last):
  File "/var/www/courtlistener/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/www/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 270, in handle
    options['action'](options)
  File "/var/www/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 227, in do_everything
    get_and_save_free_document_reports(options)
  File "/var/www/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 119, in get_and_save_free_document_reports
    result = delay['result'].get()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/result.py", line 209, in get
    self._maybe_reraise_parent_error()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/result.py", line 232, in _maybe_reraise_parent_error
    node.maybe_throw()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/result.py", line 327, in maybe_throw
    cache = self._get_task_meta() if self._cache is None else self._cache
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/result.py", line 412, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/result.py", line 406, in _maybe_set_cache
    self.on_ready(self)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/vine/promises.py", line 170, in __call__
    return self.throw()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/vine/promises.py", line 167, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/result.py", line 123, in _on_fulfilled
    self.backend.remove_pending_result(self)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/backends/asynchronous.py", line 175, in remove_pending_result
    self.on_result_fulfilled(result)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/backends/asynchronous.py", line 183, in on_result_fulfilled
    self.result_consumer.cancel_for(result.id)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/backends/redis.py", line 148, in cancel_for
    self._pubsub.unsubscribe(key)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/redis/client.py", line 3112, in unsubscribe
    retval = self.execute_command('UNSUBSCRIBE', *args)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/redis/client.py", line 3009, in execute_command
    self._execute(connection, connection.send_command, *args)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/redis/client.py", line 3013, in _execute
    return command(*args)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/redis/connection.py", line 620, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/redis/connection.py", line 613, in send_packed_command
    (errno, errmsg))
redis.exceptions.ConnectionError: Error 32 while writing to socket. Broken pipe.

I spent a bunch of time trying to find a better way to handle this, but I ultimately failed, so
instead of pulling out my hair trying to get Celery to work, I'm just going to...not use Celery (as
much).

Hopefully this will work better.