fix(client tasks): Should fix decorator mis-order causing crash
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/var/www/courtlistener/cl/corpus_importer/management/commands/georgia_state_university.py", line 435, in handle
    download_documents(options)
  File "/var/www/courtlistener/cl/corpus_importer/management/commands/georgia_state_university.py", line 357, in download_documents
    get_pacer_doc_by_rd.s(rd.pk, session.cookies,
AttributeError: 'function' object has no attribute 's'