feat(ia serializer): Use a model class instead of a hyperlinkrelatedclass
This avoids the following error:

Traceback (most recent call last):
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/courtlistener/cl/corpus_importer/tasks.py", line 141, in upload_recap_json
    d, json_str = generate_ia_json(pk, database=database)
  File "/var/www/courtlistener/cl/corpus_importer/tasks.py", line 132, in generate_ia_json
    IADocketSerializer(d).data,
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 531, in data
    ret = super(Serializer, self).data
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 500, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 500, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/rest_framework/relations.py", line 351, in to_representation
    "the serializer." % self.__class__.__name__
AssertionError: `HyperlinkedIdentityField` requires the request in the serializer context. Add `context={'request': request}` when instantiating the serializer.